#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2009-2014:
#    Gabes Jean, naparuba@gmail.com
#    Gerhard Lausser, Gerhard.Lausser@consol.de
#    Gregory Starck, g.starck@gmail.com
#    Hartmut Goebel, h.goebel@goebel-consult.de
#
# This file is part of Shinken.
#
# Shinken is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Shinken is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Shinken.  If not, see <http://www.gnu.org/licenses/>.

"""Pyro5 compatibility wrapper
===============================

Historically Shinken used Pyro3/4 for RPC-like communications.  Those
versions are no longer compatible with modern Python interpreters (for
example Python 3.13 on RHEL 9).  This module provides a very small
compatibility shim around :mod:`Pyro5` so existing call sites that
expect a ``pyro`` helper keep working while using the actively
maintained Pyro5 runtime.

Only the pieces required by the current codebase are implemented:

* :func:`create_uri` builds a Pyro5 URI for a host/port/object
  combination.
* :func:`getProxy` returns a :class:`Pyro5.api.Proxy` instance with
  optional HMAC and timeout handling compatible with the older API.

The serializer is forced to ``pickle`` to preserve compatibility with
the payloads produced by the existing daemons.
"""

from __future__ import annotations

from typing import Optional

from Pyro5 import api as pyro_api

# Ensure we stay compatible with the existing pickle-based payloads.
pyro_api.config.SERIALIZER = "pickle"
pyro_api.config.SERIALIZERS_ACCEPTED.add("pickle")


class Pyro:
    """Namespace-style access mirroring the historic helper.

    Consumers used to access ``Pyro.URI`` or ``Pyro.Proxy`` directly, so
    we expose them here for backwards compatibility while relying on the
    Pyro5 implementations under the hood.
    """

    URI = pyro_api.URI
    Proxy = pyro_api.Proxy


def create_uri(address: str, port: int | str, object_name: str, use_ssl: bool) -> pyro_api.URI:
    """Return a Pyro5 URI pointing to the requested object.

    Args:
        address: Hostname or IP address of the Pyro server.
        port: TCP port exposed by the remote daemon.
        object_name: Name of the exposed Pyro object.
        use_ssl: Whether SSL transport should be used.  When enabled the
            global Pyro5 ``SSL`` flag is set so the returned URI can be
            consumed by a TLS-capable proxy.
    """

    pyro_api.config.SSL = use_ssl
    scheme = "PYRO"
    return pyro_api.URI(f"{scheme}:{object_name}@{address}:{port}")


def getProxy(uri: pyro_api.URI | str, hmac_key: Optional[str] = None, timeout: Optional[float] = None) -> pyro_api.Proxy:
    """Create a Pyro5 proxy with optional security settings.

    Args:
        uri: URI generated by :func:`create_uri` or a compatible string.
        hmac_key: Optional HMAC key (string) applied to the proxy for
            authentication.  The key is encoded to UTF-8 to satisfy
            Pyro5's requirement for bytes.
        timeout: Optional request timeout propagated to the proxy.
    """

    proxy = pyro_api.Proxy(uri)
    if hmac_key:
        proxy._pyroHmacKey = hmac_key.encode("utf-8")
    if timeout is not None:
        proxy._pyroTimeout = timeout
    return proxy
