# Merge this peer into your existing Thruk backend configuration.
# Match the Thruk login to a contact in your .cfg files.
<Backend>
    <peer>
        name = Shinken Rust
        type = livestatus
        <options>
            peer = 127.0.0.1:6557
        </options>
    </peer>
</Backend>
